# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nan = Not a Number
email: nan.wang.28@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Notes on my journey of data science and machine learning. 
    我用这个网站记录自己在数据科学和机器学习的笔记。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nanwang.me" # the base hostname & protocol for your site
twitter_username: nanwang_t
github_username:  nan-wang

# Build settings
markdown: kramdown
